// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game-service.proto

package br.com.til.models;

public interface GameStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GameState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Player player = 1;</code>
   */
  java.util.List<br.com.til.models.Player> 
      getPlayerList();
  /**
   * <code>repeated .Player player = 1;</code>
   */
  br.com.til.models.Player getPlayer(int index);
  /**
   * <code>repeated .Player player = 1;</code>
   */
  int getPlayerCount();
  /**
   * <code>repeated .Player player = 1;</code>
   */
  java.util.List<? extends br.com.til.models.PlayerOrBuilder> 
      getPlayerOrBuilderList();
  /**
   * <code>repeated .Player player = 1;</code>
   */
  br.com.til.models.PlayerOrBuilder getPlayerOrBuilder(
      int index);
}
